# -*- coding: utf-8 -*-
"""Exercise 4: Strings Concatenation

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mCCNyoVl_IBHGbBAUu6SOZAf7U6G-Wj_
"""

#Write three strings in different variables and print the output as one string.

word1 = ("Rafael")
word2 = ("Christian")
word3 = ("Formaran")
print(word1,word2,word3)