# -*- coding: utf-8 -*-
"""Exercise 5: Computing the area of a circle

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mCCNyoVl_IBHGbBAUu6SOZAf7U6G-Wj_
"""



#Write a Python program which accepts the radius of a circle from the user and compute the area. 

print("Area of a circle calculator")
r = int(input("What is the Radius of the circle? "))
a = ((r**2)*3.14)
print("The area of the circle is:", a)