# -*- coding: utf-8 -*-
"""Exercise 2: Print the Version of Python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mCCNyoVl_IBHGbBAUu6SOZAf7U6G-Wj_
"""

#Write a Python program to get the Python version you are using.

import sys
print("Hello, This is your Python version:")
print(sys.version)