# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mCCNyoVl_IBHGbBAUu6SOZAf7U6G-Wj_
"""



#Excercise 1: Write a Python program to print the following string in a specific format.Twinkle, twinkle, little star, How I wonder what you are! Up above the world so high, Like a diamond in the sky. Twinkle, twinkle, little star, How I wonder what you are
print("Twinkle, twinkle, little star, \n\tHow I wonder what you are! \n\t\tUp above the world so high, \n\tLike a diamond in the sky. \nTwinkle, twinkle, little star, \n\tHow I wonder what you are!")