# -*- coding: utf-8 -*-
"""Exercise 3: Print date and Time

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mCCNyoVl_IBHGbBAUu6SOZAf7U6G-Wj_
"""

#Write a Python program to display the current date and time.
import datetime
now = datetime.datetime.now()
print("Current date and time : ")
print(now.strftime("%m-%d-%Y %H:%M:%S"))